.TH gosia 1 "2008 APRIL 18"
.SH NAME
gosia \- Calculates cross-sections for Coulex
.SH SYNOPSIS

Calculates cross-sections for Coulomb excitation experiments.

.SH USAGE

.BR gosia < input_file

.SH FILES

Needs an input file in a special format.


.SH HISTORY

This version was based on one downloaded from

.BR http://www.pas.rochester.edu/~cline/Research/GOSIAcodes/gosia.f

to which many comments have been added and then passed back to Adam Hayes,
and Doug Cline who are maintaining the code.
